# Generated by Django 3.1.7 on 2021-05-07 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0002_auto_20210507_1241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karyawan',
        ),
    ]
