# Generated by Django 3.1.7 on 2021-05-07 08:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strap', '0003_delete_karyawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_karyawan', models.CharField(max_length=200)),
                ('nama_karyawan', models.CharField(max_length=200)),
                ('almt_karyawan', models.CharField(max_length=100)),
                ('telp_karyawan', models.CharField(max_length=100)),
                ('ttl_karyawan', models.CharField(max_length=100)),
                ('jenkel_karyawan', models.CharField(blank=True, choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], max_length=100, null=True)),
                ('jabatan', models.CharField(blank=True, choices=[('PPAT', 'PPAT'), ('karyawan PPAT', 'karyawan PPAT'), ('karyawan Notaris', 'karyawan PPAT')], max_length=150, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Karyawan',
            },
        ),
    ]
