# Generated by Django 3.1.7 on 2021-05-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0005_akta'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
