# Generated by Django 3.1.7 on 2021-05-29 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('strap', '0006_karyawan_profile_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jenis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_jenis', models.CharField(max_length=200)),
                ('jenis', models.CharField(max_length=200)),
                ('keterangan_jenis', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Jenis Akta',
            },
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='nama_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='profile_pic',
            field=models.ImageField(blank=True, default='fotokosong.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
