# Generated by Django 3.1.7 on 2021-05-31 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0007_auto_20210529_0952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='jabatan',
            field=models.CharField(blank=True, choices=[('PPAT', 'PPAT'), ('karyawan PPAT', 'karyawan PPAT'), ('karyawan Notaris', 'karyawan Notaris')], max_length=150, null=True),
        ),
    ]
