# Generated by Django 3.1.7 on 2021-06-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0008_auto_20210531_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=200)),
                ('nama', models.CharField(max_length=200)),
                ('tempat_lahir', models.CharField(max_length=200)),
                ('tanggal_lahir', models.CharField(max_length=200)),
                ('pekerjaan', models.CharField(max_length=200)),
                ('status_kewarganegaraan', models.CharField(max_length=200)),
                ('prov', models.CharField(max_length=200)),
                ('kab', models.CharField(max_length=200)),
                ('alamat', models.CharField(max_length=200)),
                ('rt', models.CharField(max_length=200)),
                ('rw', models.CharField(max_length=200)),
                ('desa', models.CharField(max_length=200)),
                ('kec', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Data Client',
            },
        ),
    ]
