# Generated by Django 3.1.7 on 2021-06-10 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0010_auto_20210610_1342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='coba',
        ),
    ]
