# Generated by Django 3.1.7 on 2021-06-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0012_auto_20210612_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='alamat_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='desa_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='kab_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='kec_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nama_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nik_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='pekerjaan_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='prov_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='rt_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='rw_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='status_kewarganegaraan_pertama',
            field=models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='tanggal_lahir_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='tempat_lahir_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
