# Generated by Django 3.1.7 on 2021-06-17 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0014_auto_20210612_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karyawan',
            name='ttl_karyawan',
        ),
        migrations.AddField(
            model_name='karyawan',
            name='desa_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='kab_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='kec_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='nik_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='prov_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='rt_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='rw_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='status_kewarganegaraan_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tanggal_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='tempat_lahir_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
