# Generated by Django 3.1.7 on 2021-06-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0015_auto_20210617_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='alamat_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='alamat_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='desa_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='desa_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='kab_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='kab_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='kec_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='kec_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='nama_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='nama_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='nik_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='nik_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='pekerjaan_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='pekerjaan_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='prov_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='prov_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='rt_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='rt_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='rw_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='rw_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='status_kewarganegaraan_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='status_kewarganegaraan_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='tanggal_lahir_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='tanggal_lahir_pertama',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='tempat_lahir_kedua',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='tempat_lahir_pertama',
        ),
    ]
