# Generated by Django 3.1.7 on 2021-06-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0016_auto_20210617_1927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
