# Generated by Django 3.1.7 on 2021-06-17 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0018_clientsatu'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_kedua', models.IntegerField(blank=True, null=True)),
                ('nama_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kewarganegaraan_kedua', models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True)),
                ('prov_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('kab_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('rt_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('rw_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('desa_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('kec_kedua', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Data Client Pihak Kedua',
            },
        ),
    ]
