# Generated by Django 3.1.7 on 2021-06-17 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0019_clientdua'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='client_penerima',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='client_pengalih',
        ),
    ]
