# Generated by Django 3.1.7 on 2021-06-17 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0020_auto_20210617_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempClientSatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik_pertama', models.IntegerField(blank=True, null=True)),
                ('tempat_lahir_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('nama_pertama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.clientsatu')),
            ],
            options={
                'verbose_name_plural': 'TempClientSatu',
            },
        ),
    ]
