# Generated by Django 3.1.7 on 2021-06-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0021_tempclientsatu'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempclientsatu',
            name='alamat_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='desa_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='kab_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='kec_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='pekerjaan_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='prov_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='rt_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='rw_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='status_kewarganegaraan_pertama',
            field=models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='tanggal_lahir_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientsatu',
            name='nama_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
