# Generated by Django 3.1.7 on 2021-06-17 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0026_auto_20210617_2020'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailClientSatu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('nama_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kewarganegaraan_pertama', models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True)),
                ('prov_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('kab_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('rt_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('rw_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('desa_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('kec_pertama', models.CharField(blank=True, max_length=200, null=True)),
                ('nik_pertama', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.clientsatu')),
            ],
            options={
                'verbose_name_plural': 'DetailClientSatu',
            },
        ),
    ]
