# Generated by Django 3.1.7 on 2021-06-17 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0027_detailclientsatu'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailClientDua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('nama_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_lahir_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('pekerjaan_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kewarganegaraan_kedua', models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True)),
                ('prov_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('kab_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('alamat_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('rt_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('rw_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('desa_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('kec_kedua', models.CharField(blank=True, max_length=200, null=True)),
                ('nik_kedua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.clientdua')),
            ],
            options={
                'verbose_name_plural': 'DetailClientDua',
            },
        ),
    ]
