# Generated by Django 3.1.7 on 2021-06-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0028_detailclientdua'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransaksiAkta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('no_urut', models.CharField(blank=True, max_length=200, null=True)),
                ('nomor_akta', models.CharField(blank=True, max_length=200, null=True)),
                ('tgl_akta', models.CharField(blank=True, max_length=100, null=True)),
                ('jenis', models.CharField(blank=True, choices=[('AJB', 'AJB'), ('APHT', 'APHT'), ('SKMHT', 'SKMHT'), ('AH', 'AH'), ('APHB', 'APHB')], max_length=100, null=True)),
                ('nomor_hak', models.CharField(blank=True, max_length=200, null=True)),
                ('almt_aset', models.CharField(blank=True, max_length=200, null=True)),
                ('luas_tanah', models.CharField(blank=True, max_length=200, null=True)),
                ('luas_bgn', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_pengalihan', models.CharField(blank=True, max_length=200, null=True)),
                ('nop', models.CharField(blank=True, max_length=200, null=True)),
                ('njop', models.CharField(blank=True, max_length=200, null=True)),
                ('tgl_ssp', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_ssp', models.CharField(blank=True, max_length=200, null=True)),
                ('tgl_sbb', models.CharField(blank=True, max_length=200, null=True)),
                ('harga_sbb', models.CharField(blank=True, max_length=200, null=True)),
                ('keterangan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Transaksi Akta',
            },
        ),
    ]
