# Generated by Django 3.1.7 on 2021-06-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0030_auto_20210620_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientdua',
            name='nik_kedua',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
