# Generated by Django 3.1.7 on 2021-06-20 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0031_auto_20210620_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclientdua',
            name='nik_kedua',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.tempclientdua'),
        ),
        migrations.AlterField(
            model_name='detailclientsatu',
            name='nik_pertama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.tempclientsatu'),
        ),
        migrations.DeleteModel(
            name='ClientSatu',
        ),
    ]
