# Generated by Django 3.1.7 on 2021-06-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0032_auto_20210620_2349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClientDua',
        ),
    ]
