# Generated by Django 3.1.7 on 2021-06-20 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0033_delete_clientdua'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientsatu',
            name='status_kewarganegaraan_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
