# Generated by Django 3.1.7 on 2021-06-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0035_auto_20210621_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='desa_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='kab_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='kec_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='prov_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
