# Generated by Django 3.1.7 on 2021-06-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0038_auto_20210621_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='akta',
            old_name='no_urut',
            new_name='no_transaksi',
        ),
        migrations.RemoveField(
            model_name='tempakta',
            name='no_urut',
        ),
    ]
