# Generated by Django 3.1.7 on 2021-06-21 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0039_auto_20210621_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='no_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
