# Generated by Django 3.1.7 on 2021-06-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0040_auto_20210621_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='alamat_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='desa_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='kab_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='kec_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nama_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='nik_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='pekerjaan_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='prov_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='rt_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='rw_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='status_kewarganegaraan_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='status_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='tanggal_lahir_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='akta',
            name='tempat_lahir_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
