# Generated by Django 3.1.7 on 2021-06-21 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0041_auto_20210621_2009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempakta',
            name='almt_aset',
        ),
    ]
