# Generated by Django 3.1.7 on 2021-06-21 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0042_remove_tempakta_almt_aset'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempakta',
            name='alamat_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='desa_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='desa_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='jabatan_pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='jenis_bukti_perjanjian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='jenis_kuasa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='jumlah_perjanjian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='kab_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='kab_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='kec_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='kec_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='keterangan_kuasa',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='nama_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='nik_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='no_perjanjian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='pekerjaan_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='prov_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='prov_tanah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='pt',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='rt_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='rw_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='status_kewarganegaraan_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='status_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='tanggal_lahir_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='tanggal_perjanjian',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='tempat_lahir_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
