# Generated by Django 3.1.7 on 2021-06-22 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0043_auto_20210621_2011'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransaksiAkta',
        ),
    ]
