# Generated by Django 3.1.7 on 2021-06-22 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0044_delete_transaksiakta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='id_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
