# Generated by Django 3.1.7 on 2021-06-22 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0045_auto_20210622_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='nik_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='rt_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='karyawan',
            name='rw_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
