# Generated by Django 3.1.7 on 2021-06-22 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0047_tempkaryawan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailKaryawan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_transaksi', models.BigIntegerField(blank=True, null=True)),
                ('id_karyawan', models.CharField(blank=True, max_length=50, null=True)),
                ('nik_karyawan', models.CharField(blank=True, max_length=50, null=True)),
                ('nama_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('tempat_lahir_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('tanggal_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('status_kewarganegaraan_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('prov_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('kab_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('almt_karyawan', models.CharField(blank=True, max_length=100, null=True)),
                ('rt_karyawan', models.CharField(blank=True, max_length=50, null=True)),
                ('rw_karyawan', models.CharField(blank=True, max_length=50, null=True)),
                ('desa_karyawan', models.CharField(blank=True, max_length=200, null=True)),
                ('kec_karyawan', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'DetailKaryawan',
            },
        ),
    ]
