# Generated by Django 3.1.7 on 2021-06-22 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0048_detailkaryawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jenis',
            name='id_jenis',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jenis',
            name='jenis',
            field=models.CharField(max_length=100),
        ),
    ]
