# Generated by Django 3.1.7 on 2021-06-22 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0049_auto_20210622_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientsatu',
            name='nik_pertama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientsatu',
            name='rt_pertama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientsatu',
            name='rw_pertama',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
