# Generated by Django 3.1.7 on 2021-06-22 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0050_auto_20210622_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientdua',
            name='nik_kedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientdua',
            name='rt_kedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempclientdua',
            name='rw_kedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
