# Generated by Django 3.1.7 on 2021-06-22 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0052_auto_20210622_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempakta',
            name='harga_pengalihan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='harga_sbb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='harga_ssp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='luas_bgn',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='luas_tanah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='nik_saksi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='njop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='no_perjanjian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='nomor_akta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='nop',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='rt_saksi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='rw_saksi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='tanggal_perjanjian',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='tgl_akta',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='tgl_sbb',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tempakta',
            name='tgl_ssp',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
