# Generated by Django 3.1.7 on 2021-06-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0054_auto_20210622_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='almt_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='desa_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='kab_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='kec_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='nama_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='nik_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='prov_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='rt_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='rw_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='status_kewarganegaraan_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='tanggal_karyawan',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='tempat_lahir_karyawan',
        ),
    ]
