# Generated by Django 3.1.7 on 2021-06-24 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0055_auto_20210624_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempkaryawan',
            name='id_karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strap.karyawan'),
        ),
    ]
