# Generated by Django 3.1.7 on 2021-06-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0056_auto_20210624_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailclientsatu',
            name='nik_pertama',
        ),
        migrations.AddField(
            model_name='detailclientsatu',
            name='nik_kedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
