# Generated by Django 3.1.7 on 2021-06-24 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0057_auto_20210624_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailclientsatu',
            name='nik_kedua',
        ),
        migrations.AddField(
            model_name='detailclientsatu',
            name='nik_pertama',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.tempclientsatu'),
        ),
    ]
