# Generated by Django 3.1.7 on 2021-06-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0058_auto_20210624_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclientdua',
            name='nik_kedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
