# Generated by Django 3.1.7 on 2021-07-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0061_auto_20210708_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempclientdua',
            name='status_kewarganegaraan_kedua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
