# Generated by Django 3.1.7 on 2021-07-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0064_detailclientsatu_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempkaryawan',
            name='almt_karyawan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='desa_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='kab_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='kec_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='nama_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='nik_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='prov_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='rt_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='rw_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='status_kewarganegaraan_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='tanggal_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempkaryawan',
            name='tempat_lahir_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
