# Generated by Django 3.1.7 on 2021-07-10 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0066_tempkaryawan_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempkaryawan',
            name='id_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
