# Generated by Django 3.1.7 on 2021-07-10 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0068_auto_20210710_2002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailkaryawan',
            old_name='id_karyawan',
            new_name='nomor_pengenal',
        ),
        migrations.RenameField(
            model_name='karyawan',
            old_name='id_karyawan',
            new_name='nomor_pengenal',
        ),
    ]
