# Generated by Django 3.1.7 on 2021-07-10 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0069_auto_20210710_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='nomor_pengenal',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='nomor_pengenal',
        ),
        migrations.RemoveField(
            model_name='tempkaryawan',
            name='nomor_pengenal',
        ),
    ]
