# Generated by Django 3.1.7 on 2021-07-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0070_auto_20210710_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclientsatu',
            name='no_transaksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='strap.akta'),
        ),
    ]
