# Generated by Django 3.1.7 on 2021-07-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0072_auto_20210713_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='karyawan',
            name='id_karyawan',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
