# Generated by Django 3.1.7 on 2021-07-17 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0076_auto_20210717_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='no_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
