# Generated by Django 3.1.7 on 2021-07-17 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0077_auto_20210717_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclientdua',
            name='no_transaksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strap.akta'),
        ),
        migrations.AlterField(
            model_name='detailclientsatu',
            name='no_transaksi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strap.akta'),
        ),
    ]
