# Generated by Django 3.1.7 on 2021-07-23 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0079_auto_20210722_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempakta',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='tempakta',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='tempakta',
            name='tanggal',
        ),
    ]
