# Generated by Django 3.1.7 on 2021-07-23 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0080_auto_20210723_1049'),
    ]

    operations = [
        migrations.AddField(
            model_name='detailkaryawan',
            name='id_karyawan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='strap.karyawan'),
        ),
    ]
