# Generated by Django 3.1.7 on 2021-07-23 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0081_detailkaryawan_id_karyawan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='almt_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='desa_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='kab_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='kec_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='nama_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='nik_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='no_transaksi',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='prov_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='rt_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='rw_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='status_kewarganegaraan_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='tanggal_karyawan',
        ),
        migrations.RemoveField(
            model_name='detailkaryawan',
            name='tempat_lahir_karyawan',
        ),
    ]
