# Generated by Django 3.1.7 on 2021-07-28 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0082_auto_20210723_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='akta',
            name='bulan',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='tahun',
        ),
        migrations.RemoveField(
            model_name='akta',
            name='tanggal',
        ),
    ]
