# Generated by Django 3.1.7 on 2021-07-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0083_auto_20210728_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclientdua',
            name='no_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='detailclientsatu',
            name='no_transaksi',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
