# Generated by Django 3.1.7 on 2021-07-28 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0087_auto_20210728_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailclientdua',
            name='nik_kedua',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
