# Generated by Django 3.1.7 on 2021-08-09 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0090_auto_20210801_0927'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='nib',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
