# Generated by Django 3.1.7 on 2021-08-09 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0092_tempakta_nib'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='no_bukti_ppat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='no_bukti_ppat',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
