# Generated by Django 3.1.7 on 2021-08-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0093_auto_20210809_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karyawan',
            name='status_kewarganegaraan_karyawan',
            field=models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True),
        ),
    ]
