# Generated by Django 3.1.7 on 2021-08-14 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0094_auto_20210810_1640'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detailkaryawan',
            old_name='id_karyawan',
            new_name='nik_karyawan',
        ),
        migrations.RenameField(
            model_name='tempkaryawan',
            old_name='id_karyawan',
            new_name='nik_karyawan',
        ),
        migrations.RemoveField(
            model_name='karyawan',
            name='id_karyawan',
        ),
    ]
