# Generated by Django 3.1.7 on 2021-08-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0095_auto_20210814_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='akta',
            name='uraian_tl_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailclientdua',
            name='uraian_tl_kedua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='detailclientsatu',
            name='uraian_tl_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='karyawan',
            name='uraian_tl_karyawan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempakta',
            name='uraian_tl_saksi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientdua',
            name='uraian_tl_kedua',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='tempclientsatu',
            name='uraian_tl_pertama',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
