# Generated by Django 3.1.7 on 2021-08-15 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strap', '0096_auto_20210815_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='akta',
            name='status_kewarganegaraan_saksi',
            field=models.CharField(blank=True, choices=[('Warga Negara Indonesia', 'Warga Negara Indonesia'), ('Warga Negara Asing', 'Warga Negara Asing')], max_length=200, null=True),
        ),
    ]
